version: "3.9"

services:
  database:
    container_name: modular_monolith_db
    image: postgres:16.1
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: Admin123!@#
    volumes:
      - database_data
      
volumes: 
  database_data:
    name: modular_monolith_db_data
    