name: build-project
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET 8.x
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.x'
    - name: Install dependencies
      run: dotnet restore ModularMonolith.sln
    - name: Build
      run: dotnet build ModularMonolith.sln
    - name: Run Unit-Tests
      run: dotnet test --filter "FullyQualifiedName~.UnitTests"