name: Continous Integration
on:
  push:
    branches:
      - master
      - develop

jobs:
  build-test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: read
      checks: write
      packages: read

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET 8.x
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.x'
    - name: Install dependencies
      run: dotnet restore ModularMonolith.sln
    - name: Build
      run: dotnet build ModularMonolith.sln
    - name: Run Architecture-Tests
      run: dotnet test --filter "FullyQualifiedName~.ArchitectureTests"
    - name: Run Unit-Tests
      run: dotnet test --logger trx --results-directory "test-results" --filter "FullyQualifiedName~.UnitTests"
    - name: Upload Unit-Test results
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: test-results
      if: always()
    - name: Test Reporter
      uses: dorny/test-reporter@v1
      with:
        artifact: test-results
        name: dotnet tests
        path: '*.trx'
        reporter: dotnet-trx
      if: always()
