name: Continous Integration
on:
  push:
    branches:
      - master
      - develop

jobs:
  build-test:
    runs-on: ubuntu-latest
    permissions:
      statuses: write
      checks: write
      contents: write
      pull-requests: write
      actions: write

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET 8.x
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.x'
    - name: Install dependencies
      run: dotnet restore ModularMonolith.sln
    - name: Build
      run: dotnet build ModularMonolith.sln
    - name: Run Architecture-Tests
      run: dotnet test --filter "FullyQualifiedName~.ArchitectureTests"
    - name: Run Unit-Tests
      run: dotnet test --logger trx --results-directory "test-results" --collect:"XPlat Code Coverage" --filter "FullyQualifiedName~.UnitTests"
    - name: Upload Unit-Test results
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: test-results
      if: always()
    - name: Test Reporter
      uses: dorny/test-reporter@v1
      with:
        name: dotnet tests
        path: 'test-results/*.trx'
        reporter: dotnet-trx
      if: always()
    - name: Code Coverage Report
      uses: irongut/CodeCoverageSummary@v1.3.0
      with:
        filename: test-results/**/coverage.cobertura.xml
        badge: true
        fail_below_min: true
        format: markdown
        hide_branch_rate: false
        hide_complexity: false
        indicators: true
        output: both
        thresholds: '60 80'
