name: Continous Integration
on:
  push:
    branches:
      - master
      - develop

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET 8.x
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.x'
    - name: Install dependencies
      run: dotnet restore ModularMonolith.sln
    - name: Build
      run: dotnet build ModularMonolith.sln
    - name: Run Architecture-Tests
      run: dotnet test --filter "FullyQualifiedName~.ArchitectureTests"
    - name: Run Unit-Tests
      run: dotnet test --logger trx --results-directory "TestResults" --filter "FullyQualifiedName~.UnitTests"
    - name: Upload Unit-Test results
      uses: actions/upload-artifact@v3
      with:
        name: dotnet-results-8.x
        path: TestResults
      if: always()
    - name: Test Reporter
      uses: dorny/test-reporter@v1.7.0
      with:
        name: dotnet tests
        path: TestResults/*.trx
        reporter: dotnet-trx
      if: always()
  