---
name: Publish

on:
  workflow_call:
    inputs:
      release_tag:
        description: Semantic release version
        required: true
        type: string

  workflow_dispatch:
    inputs:
      release_tag:
        description: Semantic release version
        required: true
        type: string

permissions:
  id-token: write
  contents: write
  packages: write
  pull-requests: write
  security-events: write

jobs:

  sast:
    name: Validate code
    uses: ./.github/workflows/sast-scan.yaml
    permissions:
      contents: write
    with:
      rules: "p/csharp"
      upload-artifact: true
      upload-release-assets: true
      upload-results-github-security: true
      release-tag: ${{ inputs.release_tag }}


  build_image:
    name: Build docker image
    runs-on: ubuntu-latest
    env:
      REGISTRY: docker.io
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2.2.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2.9.0
        id: buildx

      - name: Log in to Dockerhub
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.dockerhub_username }}
          password: ${{ secrets.dockerhub_password }}

      - name: Extract metadata for docker
        uses: docker/metadata-action@v4
        id: metadata
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository }}
          tags: |
            type=raw,value=latest
            type=sha
            type=sha,format=long
            type=semver,pattern={{version}},value=${{ inputs.release_tag }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          target: production
          push: true
          builder: ${{ steps.buildx.outputs.name }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}

      - name: Create Docker image URL
        id: build_image_url
        run: |
          echo "image_url=${{ env.REGISTRY }}/${{ github.repository }}:${{ inputs.release_tag }}" | tr '[:upper:] '[:lower:]' >> "$GITHUB_OUTPUT"

      - name: Release Update - ${{ inputs.release_tag }}
        uses: softprops/action-gh-release@v1
        env:
          REGISTRY: ${{ env.REGISTRY }}
          REPOSITORY: ${{ github.repository }}
        with:
          tag_name: "v${{ inputs.release_tag }}"
          append_body: true
          body: |
            - Dockerhub container URL: ${{ steps.build_image_url.outputs.image_url }}
          token: ${{ secrets.GITHUB_TOKEN }}
