---

name: Run Tests

on:
  pull_request_target:
    types:
    - opened
    - edited
    - synchronize

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  dotnet-test:
    name: Run solution tests
    runs-on: ubuntu-latest
    permissions:
      statuses: write
      checks: write
      contents: write
      pull-requests: write
      actions: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: Setup .NET 8.x
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.x'

      - name: Install dependencies
        run: dotnet restore ModularMonolith.sln

      - name: Build
        run: dotnet build ModularMonolith.sln

      - name: Run Tests
        run: dotnet test --logger trx --results-directory "test-results" --collect:"XPlat Code Coverage" --filter "FullyQualifiedName~.UnitTests"

      - name: Upload Unit-Test results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: test-results
        if: ${{ !cancelled() }}

      - name: Test Reporter
        uses: dorny/test-reporter@v1
        with:
          name: dotnet tests
          path: 'test-results/*.trx'
          reporter: dotnet-trx
        if: ${{ !cancelled() }}

      - name: Code Coverage Report
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: test-results/**/coverage.cobertura.xml
          badge: true
          fail_below_min: true
          format: markdown
          hide_branch_rate: false
          hide_complexity: false
          indicators: true
          output: both
          thresholds: '60 80'
