---

name: Run Tests

on:
  pull_request_target:
    types:
    - opened
    - edited
    - synchronize

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  dotnet-test:
    name: Run solution tests
    runs-on: ubuntu-latest
    permissions:
      statuses: write
      checks: write
      contents: write
      pull-requests: write
      actions: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: Setup .NET 8.x
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.x'

      - name: Install dependencies
        run: |
          dotnet restore ModularMonolith.sln
          dotnet tool install -g dotnet-reportgenerator-globaltool

      - name: Build
        run: dotnet build ModularMonolith.sln

      - name: Run Tests
        run: dotnet test --logger trx --results-directory "test-results" --collect:"XPlat Code Coverage"

      - name: Generate report
        run: reportgenerator "-reports:test-results/*/*.xml" "-targetdir:coverage" "-reporttypes:Cobertura;"

      - name: Upload Unit-Test results
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: coverage
        if: ${{ !cancelled() }}

      - name: Code Coverage Report
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: coverage/**/Cobertura.xml
          badge: true
          fail_below_min: true
          format: markdown
          hide_branch_rate: false
          hide_complexity: false
          indicators: true
          output: both
          thresholds: '50 80'
